services:
  db:
    image: postgres:14-alpine
    container_name: hotfeed-db
    environment:
      POSTGRES_DB: hotfeed
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: hotfeed-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  web:
    build: .
    container_name: hotfeed-web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: dev-secret-key-for-docker
      DEBUG: "True"
      ALLOWED_HOSTS: "*"
      DB_NAME: hotfeed
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:

