# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-10-24 16:01
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "feed_like",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("like_count", models.IntegerField(db_index=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "feed_post",
                "ordering": ["-like_count", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-like_count", "-created_at"], name="feed_post_hot_idx"
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="feed.Post",
            ),
        ),
        migrations.AddIndex(
            model_name="like",
            index=models.Index(fields=["created_at"], name="feed_like_created_idx"),
        ),
        migrations.AddIndex(
            model_name="like",
            index=models.Index(
                fields=["post", "created_at"], name="feed_like_post_time_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together=set([("user_id", "post")]),
        ),
    ]
